#!/bin/bash

which docker
docker info
env

# setup docker hook
# this works 20200912 on docker hub automated build
cp docker /usr/local/bin
which docker
env
docker info

# maybe not needed
export PATH=$PWD:$PATH
which docker
env
docker info


TARGET=$(basename $DOCKER_REPO)
cd $TARGET
./run.sh
