#!/bin/bash

indent() { sed 's/^/  /'; }


which docker
docker info | indent
env | indent

# setup docker hook
cp docker /usr/local/bin
which docker
env | indent
docker info | indent

export PATH=$PWD:$PATH
which docker
env | indent
docker info | indent
exit


TARGET=$(basename $DOCKER_REPO)
cd $TARGET
./run.sh
