#!/bin/bash

docker info
which docker
env

# setup docker hook
cp docker /usr/local/bin
which docker
env
docker info

export PATH=$PWD:$PATH
env
docker info
exit


TARGET=$(basename $DOCKER_REPO)
cd $TARGET
./run.sh
