#!/bin/bash

# read cred from env and manually login (dockerhub automated build + unknown condition, push failed with auth err)
cred=$(echo $DOCKERCFG | python3 -c 'import sys,json; print(json.loads(sys.stdin.read())["https://registry-1.docker.io/v1/"]["auth"])' | base64 -d)
/usr/bin/docker login -u $(echo $cred | cut -d: -f1) -p $(echo $cred | cut -d: -f2)

# docker push $IMAGE_NAME
for i in $(cat); do
  name=$(echo $i | cut -d/ -f2)

  # docker tag ${i}:dev-amd64 yaamai/${name}:dev-amd64
  # docker tag ${i}:dev-arm64 yaamai/${name}:dev-arm64

  /usr/bin/docker push yaamai/${name}:dev-arm64 || true
  /usr/bin/docker push yaamai/${name}:dev-amd64 || true
done << EOF
goharbor/chartmuseum-photon
goharbor/redis-photon
goharbor/trivy-adapter-photon
goharbor/harbor-registryctl
goharbor/registry-photon
goharbor/nginx-photon
goharbor/harbor-log
goharbor/harbor-jobservice
goharbor/harbor-core
goharbor/harbor-portal
goharbor/harbor-db
goharbor/prepare
EOF

