#!/bin/bash

# read cred from env and manually login (dockerhub automated build + unknown condition, push failed with auth err)
cred=$(echo $DOCKERCFG | python3 -c 'import sys,json; print(json.loads(sys.stdin.read())["https://registry-1.docker.io/v1/"]["auth"])' | base64 -d)
/usr/bin/docker login -u $(echo $cred | cut -d: -f1) -p $(echo $cred | cut -d: -f2)

# docker push $IMAGE_NAME
for i in $(cat); do
  name=$(echo $i | cut -d/ -f2 | cut -d: -f1)
  docker tag $i yaamai/${name}:latest
  /usr/bin/docker push yaamai/${name}:latest
done << EOF
goharbor/redis-photon:dev
goharbor/harbor-registryctl:dev
goharbor/registry-photon:dev
goharbor/nginx-photon:dev
goharbor/harbor-log:dev
goharbor/harbor-jobservice:dev
goharbor/harbor-core:dev
goharbor/harbor-portal:dev
goharbor/harbor-db:dev
goharbor/prepare:dev
goharbor/harbor-chartserver-base:dev
goharbor/swagger:v0.21.0
EOF

